// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:372


#include "DDSMessengerC.h"
#include "tao/CDR.h"
#include "tao/ORB_Core.h"

#if !defined (__ACE_INLINE__)
#include "DDSMessengerC.inl"
#endif /* !defined INLINE */


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\sequence_cs.cpp:104



#if !defined (_DDSMESSENGER_MESSAGE__TAO_SEQ_CORBA_OCTET__CS_)
#define _DDSMESSENGER_MESSAGE__TAO_SEQ_CORBA_OCTET__CS_

DDSMessenger::Message::_tao_seq_CORBA_Octet_::_tao_seq_CORBA_Octet_ (
    ::CORBA::ULong max)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (max)
{}

DDSMessenger::Message::_tao_seq_CORBA_Octet_::_tao_seq_CORBA_Octet_ (
    ::CORBA::ULong max,
    ::CORBA::ULong length,
    ::CORBA::Octet * buffer,
    ::CORBA::Boolean release)
  : ::TAO::unbounded_value_sequence< ::CORBA::Octet>
    (max, length, buffer, release)
{}

#endif /* end #if !defined */
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\cdr_op_cs.cpp:92

#if !defined _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__CPP_
#define _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__CPP_

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSMessenger::Message::_tao_seq_CORBA_Octet_ &_tao_sequence)
{
  return TAO::marshal_sequence(strm, _tao_sequence);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSMessenger::Message::_tao_seq_CORBA_Octet_ &_tao_sequence)
{
  return TAO::demarshal_sequence(strm, _tao_sequence);
}


TAO_END_VERSIONED_NAMESPACE_DECL

#endif /* _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__CPP_ */
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSMessenger::Message &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.from.in ()) &&
    (strm << _tao_aggregate.subject.in ()) &&
    (strm << _tao_aggregate.subject_id) &&
    (strm << _tao_aggregate.text.in ()) &&
    (strm << _tao_aggregate.content) &&
    (strm << _tao_aggregate.domain_id) &&
    true;
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSMessenger::Message &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.from.out ()) &&
    (strm >> _tao_aggregate.subject.out ()) &&
    (strm >> _tao_aggregate.subject_id) &&
    (strm >> _tao_aggregate.text.out ()) &&
    (strm >> _tao_aggregate.content) &&
    (strm >> _tao_aggregate.domain_id) &&
    true;
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_cs.cpp:48


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSMessenger::Heartbeat &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.use_id) &&
    (strm << _tao_aggregate.index) &&
    true;
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSMessenger::Heartbeat &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.use_id) &&
    (strm >> _tao_aggregate.index) &&
    true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



