// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:148

#ifndef _TAO_IDL_DDSMESSENGERTYPESUPPORTC_JLVOGW_H_
#define _TAO_IDL_DDSMESSENGERTYPESUPPORTC_JLVOGW_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "DDSMessengerC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace DDSMessenger
{

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSMessenger::Message, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MessageSeq;
  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_MESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _DDSMESSENGER_MESSAGETYPESUPPORT__VAR_OUT_CH_

  class MessageTypeSupport;
  using MessageTypeSupport_ptr = MessageTypeSupport*;
  using MessageTypeSupport_var = TAO_Objref_Var_T<MessageTypeSupport>;
  using MessageTypeSupport_out = TAO_Objref_Out_T<MessageTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  MessageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = MessageTypeSupport_ptr;
    using _var_type = MessageTypeSupport_var;
    using _out_type = MessageTypeSupport_out;

    // The static operations.
    static MessageTypeSupport_ptr _duplicate (MessageTypeSupport_ptr obj);

    static void _tao_release (MessageTypeSupport_ptr obj);

    static MessageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::DDSMessenger::Message & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDSMessenger::Message * create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::DDSMessenger::Message & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::DDSMessenger::Message & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::DDSMessenger::Message & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::DDSMessenger::Message & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::DDSMessenger::Message_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::DDSMessenger::Message_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageTypeSupport ();

    

    virtual ~MessageTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MessageTypeSupport (const MessageTypeSupport &) = delete;
    MessageTypeSupport (MessageTypeSupport &&) = delete;
    MessageTypeSupport &operator= (const MessageTypeSupport &) = delete;
    MessageTypeSupport &operator= (MessageTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_MESSAGEDATAWRITER__VAR_OUT_CH_)
#define _DDSMESSENGER_MESSAGEDATAWRITER__VAR_OUT_CH_

  class MessageDataWriter;
  using MessageDataWriter_ptr = MessageDataWriter*;
  using MessageDataWriter_var = TAO_Objref_Var_T<MessageDataWriter>;
  using MessageDataWriter_out = TAO_Objref_Out_T<MessageDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  MessageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = MessageDataWriter_ptr;
    using _var_type = MessageDataWriter_var;
    using _out_type = MessageDataWriter_out;

    // The static operations.
    static MessageDataWriter_ptr _duplicate (MessageDataWriter_ptr obj);

    static void _tao_release (MessageDataWriter_ptr obj);

    static MessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSMessenger::Message & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSMessenger::Message & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSMessenger::Message & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSMessenger::Message & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSMessenger::Message & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSMessenger::Message & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSMessenger::Message & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSMessenger::Message & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSMessenger::Message & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSMessenger::Message & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageDataWriter ();

    

    virtual ~MessageDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MessageDataWriter (const MessageDataWriter &) = delete;
    MessageDataWriter (MessageDataWriter &&) = delete;
    MessageDataWriter &operator= (const MessageDataWriter &) = delete;
    MessageDataWriter &operator= (MessageDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_MESSAGEDATAREADER__VAR_OUT_CH_)
#define _DDSMESSENGER_MESSAGEDATAREADER__VAR_OUT_CH_

  class MessageDataReader;
  using MessageDataReader_ptr = MessageDataReader*;
  using MessageDataReader_var = TAO_Objref_Var_T<MessageDataReader>;
  using MessageDataReader_out = TAO_Objref_Out_T<MessageDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  MessageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = MessageDataReader_ptr;
    using _var_type = MessageDataReader_var;
    using _out_type = MessageDataReader_out;

    // The static operations.
    static MessageDataReader_ptr _duplicate (MessageDataReader_ptr obj);

    static void _tao_release (MessageDataReader_ptr obj);

    static MessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MessageDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSMessenger::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSMessenger::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSMessenger::Message & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSMessenger::Message & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSMessenger::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSMessenger::MessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSMessenger::MessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSMessenger::Message & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSMessenger::Message & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MessageDataReader ();

    

    virtual ~MessageDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    MessageDataReader (const MessageDataReader &) = delete;
    MessageDataReader (MessageDataReader &&) = delete;
    MessageDataReader &operator= (const MessageDataReader &) = delete;
    MessageDataReader &operator= (MessageDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module DDSMessenger
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace DDSMessenger
{

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DDSMessenger::Heartbeat, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> HeartbeatSeq;
  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_HEARTBEATTYPESUPPORT__VAR_OUT_CH_)
#define _DDSMESSENGER_HEARTBEATTYPESUPPORT__VAR_OUT_CH_

  class HeartbeatTypeSupport;
  using HeartbeatTypeSupport_ptr = HeartbeatTypeSupport*;
  using HeartbeatTypeSupport_var = TAO_Objref_Var_T<HeartbeatTypeSupport>;
  using HeartbeatTypeSupport_out = TAO_Objref_Out_T<HeartbeatTypeSupport>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  HeartbeatTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = HeartbeatTypeSupport_ptr;
    using _var_type = HeartbeatTypeSupport_var;
    using _out_type = HeartbeatTypeSupport_out;

    // The static operations.
    static HeartbeatTypeSupport_ptr _duplicate (HeartbeatTypeSupport_ptr obj);

    static void _tao_release (HeartbeatTypeSupport_ptr obj);

    static HeartbeatTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static HeartbeatTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static HeartbeatTypeSupport_ptr _nil ();

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::DDSMessenger::Heartbeat & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDSMessenger::Heartbeat create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::DDSMessenger::Heartbeat & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::DDSMessenger::Heartbeat & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::DDSMessenger::Heartbeat & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::DDSMessenger::Heartbeat & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::DDSMessenger::Heartbeat_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::DDSMessenger::Heartbeat_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    HeartbeatTypeSupport ();

    

    virtual ~HeartbeatTypeSupport () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    HeartbeatTypeSupport (const HeartbeatTypeSupport &) = delete;
    HeartbeatTypeSupport (HeartbeatTypeSupport &&) = delete;
    HeartbeatTypeSupport &operator= (const HeartbeatTypeSupport &) = delete;
    HeartbeatTypeSupport &operator= (HeartbeatTypeSupport &&) = delete;
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_HEARTBEATDATAWRITER__VAR_OUT_CH_)
#define _DDSMESSENGER_HEARTBEATDATAWRITER__VAR_OUT_CH_

  class HeartbeatDataWriter;
  using HeartbeatDataWriter_ptr = HeartbeatDataWriter*;
  using HeartbeatDataWriter_var = TAO_Objref_Var_T<HeartbeatDataWriter>;
  using HeartbeatDataWriter_out = TAO_Objref_Out_T<HeartbeatDataWriter>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  HeartbeatDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = HeartbeatDataWriter_ptr;
    using _var_type = HeartbeatDataWriter_var;
    using _out_type = HeartbeatDataWriter_out;

    // The static operations.
    static HeartbeatDataWriter_ptr _duplicate (HeartbeatDataWriter_ptr obj);

    static void _tao_release (HeartbeatDataWriter_ptr obj);

    static HeartbeatDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static HeartbeatDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static HeartbeatDataWriter_ptr _nil ();

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DDSMessenger::Heartbeat & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DDSMessenger::Heartbeat & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DDSMessenger::Heartbeat & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DDSMessenger::Heartbeat & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DDSMessenger::Heartbeat & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DDSMessenger::Heartbeat & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DDSMessenger::Heartbeat & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DDSMessenger::Heartbeat & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSMessenger::Heartbeat & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSMessenger::Heartbeat & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    HeartbeatDataWriter ();

    

    virtual ~HeartbeatDataWriter () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    HeartbeatDataWriter (const HeartbeatDataWriter &) = delete;
    HeartbeatDataWriter (HeartbeatDataWriter &&) = delete;
    HeartbeatDataWriter &operator= (const HeartbeatDataWriter &) = delete;
    HeartbeatDataWriter &operator= (HeartbeatDataWriter &&) = delete;
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_interface.cpp:742

  

#if !defined (_DDSMESSENGER_HEARTBEATDATAREADER__VAR_OUT_CH_)
#define _DDSMESSENGER_HEARTBEATDATAREADER__VAR_OUT_CH_

  class HeartbeatDataReader;
  using HeartbeatDataReader_ptr = HeartbeatDataReader*;
  using HeartbeatDataReader_var = TAO_Objref_Var_T<HeartbeatDataReader>;
  using HeartbeatDataReader_out = TAO_Objref_Out_T<HeartbeatDataReader>;

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:39

  

  class  HeartbeatDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    using _ptr_type = HeartbeatDataReader_ptr;
    using _var_type = HeartbeatDataReader_var;
    using _out_type = HeartbeatDataReader_out;

    // The static operations.
    static HeartbeatDataReader_ptr _duplicate (HeartbeatDataReader_ptr obj);

    static void _tao_release (HeartbeatDataReader_ptr obj);

    static HeartbeatDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static HeartbeatDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static HeartbeatDataReader_ptr _nil ();

    virtual ::DDS::ReturnCode_t read (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DDSMessenger::HeartbeatSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DDSMessenger::HeartbeatSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DDSMessenger::Heartbeat & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DDSMessenger::Heartbeat & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DDSMessenger::HeartbeatSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DDSMessenger::HeartbeatSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DDSMessenger::HeartbeatSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DDSMessenger::Heartbeat & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DDSMessenger::Heartbeat & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_interface\interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id () const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    HeartbeatDataReader ();

    

    virtual ~HeartbeatDataReader () = default;
  
  private:
    // Private and unimplemented for concrete interfaces.
    HeartbeatDataReader (const HeartbeatDataReader &) = delete;
    HeartbeatDataReader (HeartbeatDataReader &&) = delete;
    HeartbeatDataReader &operator= (const HeartbeatDataReader &) = delete;
    HeartbeatDataReader &operator= (HeartbeatDataReader &&) = delete;
  };


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module DDSMessenger
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DDSMESSENGER_MESSAGETYPESUPPORT__TRAITS_)
#define _DDSMESSENGER_MESSAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::MessageTypeSupport>
  {
    static ::DDSMessenger::MessageTypeSupport_ptr duplicate (::DDSMessenger::MessageTypeSupport_ptr p);
    static void release (::DDSMessenger::MessageTypeSupport_ptr p);
    static ::DDSMessenger::MessageTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::MessageTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSMESSENGER_MESSAGEDATAWRITER__TRAITS_)
#define _DDSMESSENGER_MESSAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::MessageDataWriter>
  {
    static ::DDSMessenger::MessageDataWriter_ptr duplicate (::DDSMessenger::MessageDataWriter_ptr p);
    static void release (::DDSMessenger::MessageDataWriter_ptr p);
    static ::DDSMessenger::MessageDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::MessageDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSMESSENGER_MESSAGEDATAREADER__TRAITS_)
#define _DDSMESSENGER_MESSAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::MessageDataReader>
  {
    static ::DDSMessenger::MessageDataReader_ptr duplicate (::DDSMessenger::MessageDataReader_ptr p);
    static void release (::DDSMessenger::MessageDataReader_ptr p);
    static ::DDSMessenger::MessageDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::MessageDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSMESSENGER_HEARTBEATTYPESUPPORT__TRAITS_)
#define _DDSMESSENGER_HEARTBEATTYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::HeartbeatTypeSupport>
  {
    static ::DDSMessenger::HeartbeatTypeSupport_ptr duplicate (::DDSMessenger::HeartbeatTypeSupport_ptr p);
    static void release (::DDSMessenger::HeartbeatTypeSupport_ptr p);
    static ::DDSMessenger::HeartbeatTypeSupport_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::HeartbeatTypeSupport_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSMESSENGER_HEARTBEATDATAWRITER__TRAITS_)
#define _DDSMESSENGER_HEARTBEATDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::HeartbeatDataWriter>
  {
    static ::DDSMessenger::HeartbeatDataWriter_ptr duplicate (::DDSMessenger::HeartbeatDataWriter_ptr p);
    static void release (::DDSMessenger::HeartbeatDataWriter_ptr p);
    static ::DDSMessenger::HeartbeatDataWriter_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::HeartbeatDataWriter_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DDSMESSENGER_HEARTBEATDATAREADER__TRAITS_)
#define _DDSMESSENGER_HEARTBEATDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DDSMessenger::HeartbeatDataReader>
  {
    static ::DDSMessenger::HeartbeatDataReader_ptr duplicate (::DDSMessenger::HeartbeatDataReader_ptr p);
    static void release (::DDSMessenger::HeartbeatDataReader_ptr p);
    static ::DDSMessenger::HeartbeatDataReader_ptr nil ();
    static ::CORBA::Boolean marshal (const ::DDSMessenger::HeartbeatDataReader_ptr p,TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "DDSMessengerTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

