// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.2
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:148

#ifndef _TAO_IDL_DDSMESSENGERC_07QY5A_H_
#define _TAO_IDL_DDSMESSENGERC_07QY5A_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#if TAO_MAJOR_VERSION != 4 || TAO_MINOR_VERSION != 0 || TAO_MICRO_VERSION != 2
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:34

namespace DDSMessenger
{
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct Message;
  using Message_var = ::TAO_Var_Var_T<Message>;
  using Message_out = ::TAO_Out_T<Message>;

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  Message
  {
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = Message_var;
    using _out_type = Message_out;
    
    ::TAO::String_Manager from;
    ::TAO::String_Manager subject;
    ::CORBA::Long subject_id;
    ::TAO::String_Manager text;
    

    
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\sequence_ch.cpp:98

    

#if !defined (_DDSMESSENGER_MESSAGE__TAO_SEQ_CORBA_OCTET__CH_)
#define _DDSMESSENGER_MESSAGE__TAO_SEQ_CORBA_OCTET__CH_

    

    class  _tao_seq_CORBA_Octet_
      : public
          ::TAO::unbounded_value_sequence< ::CORBA::Octet>
    {
    public:
      _tao_seq_CORBA_Octet_ () = default;
      _tao_seq_CORBA_Octet_ (::CORBA::ULong max);
      _tao_seq_CORBA_Octet_ (
        ::CORBA::ULong max,
        ::CORBA::ULong length,
        ::CORBA::Octet* buffer,
        ::CORBA::Boolean release = false);
      _tao_seq_CORBA_Octet_ (const _tao_seq_CORBA_Octet_ &) = default;
      _tao_seq_CORBA_Octet_ (_tao_seq_CORBA_Octet_ &&) = default;
      _tao_seq_CORBA_Octet_& operator= (const _tao_seq_CORBA_Octet_ &) = default;
      _tao_seq_CORBA_Octet_& operator= (_tao_seq_CORBA_Octet_ &&) = default;
      virtual ~_tao_seq_CORBA_Octet_ () = default;
      

      
#if (TAO_NO_COPY_OCTET_SEQUENCES == 1)
      _tao_seq_CORBA_Octet_ (::CORBA::ULong length, const ACE_Message_Block* mb)
        : ::TAO::unbounded_value_sequence< ::CORBA::Octet> (length, mb) {}
      
#endif /* TAO_NO_COPY_OCTET_SEQUENCE == 1 */
    };

#endif /* end #if !defined */
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_field\field_ch.cpp:338

    typedef _tao_seq_CORBA_Octet_ _content_seq;
    _tao_seq_CORBA_Octet_ content;
    ::CORBA::Long domain_id;
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:258

  

  struct Heartbeat;
  using Heartbeat_var = ::TAO_Fixed_Var_T<Heartbeat>;
  using Heartbeat_out = Heartbeat&;

  
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\structure_ch.cpp:47

  

  struct  Heartbeat
  {
    // TAO_IDL - Generated from
    // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_type.cpp:297

    
    using _var_type = Heartbeat_var;
    using _out_type = Heartbeat_out;
    
    ::CORBA::Long use_id;
    ::CORBA::Long index;
  };


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_module\module_ch.cpp:62


} // module DDSMessenger
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::DDSMessenger::Message>
    : public
        Var_Size_Arg_Traits_T<
            ::DDSMessenger::Message,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
  // TAO_IDL - Generated from
  // E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_arg_traits.cpp:931

  

  template<>
  class Arg_Traits< ::DDSMessenger::Heartbeat>
    : public
        Fixed_Size_Arg_Traits_T<
            ::DDSMessenger::Heartbeat,
            TAO::Any_Insert_Policy_Noop
          >
  {
  };
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDSMessenger::Message &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDSMessenger::Message &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_sequence\cdr_op_ch.cpp:64



#if !defined _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__H_
#define _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__H_
TAO_BEGIN_VERSIONED_NAMESPACE_DECL


 ::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const DDSMessenger::Message::_tao_seq_CORBA_Octet_ &_tao_sequence);
 ::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    DDSMessenger::Message::_tao_seq_CORBA_Octet_ &_tao_sequence);

TAO_END_VERSIONED_NAMESPACE_DECL



#endif /* _TAO_CDR_OP_DDSMessenger_Message__tao_seq_CORBA_Octet__H_ */
// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_visitor_structure\cdr_op_ch.cpp:37


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const DDSMessenger::Heartbeat &);
 ::CORBA::Boolean operator>> (TAO_InputCDR &, DDSMessenger::Heartbeat &);

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// E:\OpenDDS-3.31.0\ace_wrappers\tao\TAO_IDL\be\be_codegen.cpp:1648

#if defined (__ACE_INLINE__)
#include "DDSMessengerC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

